language: python
cache: pip
dist: xenial

sudo: false

matrix:
    fast_finish: true
    include:
      - { python: "3.5", env: DJANGO=2.1 }
      - { python: "3.5", env: DJANGO=master }

      - { python: "3.6", env: DJANGO=2.1 }
      - { python: "3.6", env: DJANGO=master }

      - { python: "3.7", env: DJANGO=2.1 }
      - { python: "3.7", env: DJANGO=master }

      - { python: "3.7", env: TOXENV=lint }

      - python: "3.7"
        env: TOXENV=dist
        script:
          - python setup.py bdist_wheel
          - rm -r django_permissions_auditor.egg-info
          - tox --installpkg ./dist/django_permissions_auditor-*.whl
          - tox

    allow_failures:
      - env: DJANGO=master

install:
    - pip install tox tox-venv tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
